//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BatchAudioStreamEncoder.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BatchAudioStreamEncoder.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please set vlc.exe location.
        /// </summary>
        internal static string PleaseSetVLCLocationText {
            get {
                return ResourceManager.GetString("PleaseSetVLCLocationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC Executable not found at {0}.
        /// </summary>
        internal static string VLCNotFoundAtText {
            get {
                return ResourceManager.GetString("VLCNotFoundAtText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC executable not found in the default location. 
        ///
        ///Please ensure VLC is installed.
        ///
        ///If you have installed VLC to a custom location, please set this location manually on the following screen.
        ///
        ///VLC can be downloaded from http://www.videolan.org.
        /// </summary>
        internal static string VLCNotFoundText {
            get {
                return ResourceManager.GetString("VLCNotFoundText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to VLC not found.
        /// </summary>
        internal static string VLCNotFoundTitle {
            get {
                return ResourceManager.GetString("VLCNotFoundTitle", resourceCulture);
            }
        }
    }
}
